#!/usr/bin/python3
import os
pyfile = os.environ.get('PYFILE')
pycfile = pyfile + 'c'

os.system(f'python3 -m compileall {pyfile}')
os.rename(f'__pycache__/{pyfile}'+ 'c', pycfile)
os.rmdir('__pycache__')

print(f'Compiling {pyfile} ...')
